image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: >
        cp .env.example .env;
        pipenv install;
    - command: python3 create-database.py;
        pipenv run init;
        pipenv run migrate;
        pipenv run upgrade;
        pipenv run start;
    - command: python3 welcome.py
