"""empty message

Revision ID: b2030211bfb6
Revises: e5198d8dd732
Create Date: 2019-06-12 16:51:46.629992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2030211bfb6'
down_revision = 'e5198d8dd732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('gender', sa.String(length=1), nullable=True))
    op.add_column('person', sa.Column('image_url', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'image_url')
    op.drop_column('person', 'gender')
    # ### end Alembic commands ###
